/* empty css                      */import{a as w,S as q,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",S="54322887-b96a62a676a9ab44083e67caf",E=15;async function u(r,t){return(await w.get(v,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:E}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(a=>`
    <li class="gallery-item">
      <a href="${a.largeImageURL}">
        <img src="${a.webformatURL}" alt="${a.tags}" loading="lazy">
      </a>
      <div class="info">
        <p><b>Likes:</b> ${a.likes}</p>
        <p><b>Views:</b> ${a.views}</p>
        <p><b>Comments:</b> ${a.comments}</p>
        <p><b>Downloads:</b> ${a.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function M(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function B(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}const b=document.querySelector(".form"),$=document.querySelector(".load-more");let i="",s=1,l=0;b.addEventListener("submit",R);$.addEventListener("click",O);async function R(r){if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),!i){n.warning({message:"Please enter a search query"});return}s=1,M(),L(),p();try{const t=await u(i,s);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),l=Math.ceil(t.totalHits/15),s<l&&B()}catch{n.error({message:"Request failed. Try again later."})}finally{g(),b.reset()}}async function O(){s+=1,p();try{const r=await u(i,s);h(r.hits),x(),s>=l&&(L(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Request failed."})}finally{g()}}function x(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
